export const categories = [
    {
      "id": 1001,
      "imageUrl": "../public/images/MK image.png",
      // "imageUrl": "https://hub.dummyapis.com/Image?text=MK&height=120&width=120",
      "firstName": "Marlen",
      "lastName": "Kutch",
      "email": "Marlen.Kutch@dummyapis.com",
      "contactNumber": "4717296300",
      "age": 33,
      "dob": "27/10/1991",
      "address": "Address1",
      "designation": "Director"
    },
    {
      "id": 1002,
      "imageUrl": "../public/images/BP image.png",
      "firstName": "Barton",
      "lastName": "Prosacco",
      "email": "Barton.Prosacco@dummyapis.com",
      "contactNumber": "4342494844",
      "age": 31,
      "dob": "30/07/1993",
      "address": "Address2",
      "designation": "Manager",
      "managerId": 1001
    },
    {
      "id": 1003,
      "imageUrl": "../public/images/VR image.png",
      "firstName": "Viola",
      "lastName": "Reynolds",
      "email": "Viola.Reynolds@dummyapis.com",
      "contactNumber": "4523097085",
      "age": 69,
      "dob": "20/11/1955",
      "address": "Address3",
      "designation": "Manager",
      "managerId": 1001
    },
    {
      "id": 1004,
      "imageUrl": "../public/images/PK image.png",
      "firstName": "Pink",
      "lastName": "Keeling",
      "email": "Pink.Keeling@dummyapis.com",
      "contactNumber": "4750599785",
      "age": 71,
      "dob": "05/12/1953",
      "address": "Address4",
      "designation": "Developer",
      "managerId": 1003
    },
    {
      "id": 1005,
      "imageUrl": "../public/images/WD image.png",
      "firstName": "Will",
      "lastName": "Daniel",
      "email": "Will.Daniel@dummyapis.com",
      "contactNumber": "4365697566",
      "age": 83,
      "dob": "11/06/1941",
      "address": "Address5",
      "designation": "Designer",
      "managerId": 1003
    },
    {
      "id": 1006,
      "imageUrl": "../public/images/NW imge.png",
      "firstName": "Nola",
      "lastName": "Willms",
      "email": "Nola.Willms@dummyapis.com",
      "contactNumber": "4711593167",
      "age": 27,
      "dob": "18/05/1997",
      "address": "Address6",
      "designation": "Developer",
      "managerId": 1002
    },
    {
      "id": 1007,
      "imageUrl": "../public/images/DA image.png",
      "firstName": "Destiny",
      "lastName": "Ankunding",
      "email": "Destiny.Ankunding@dummyapis.com",
      "contactNumber": "4131896121",
      "age": 71,
      "dob": "26/05/1953",
      "address": "Address7",
      "designation": "Designer",
      "managerId": 1002
    },
    {
      "id": 1008,
      "imageUrl": "../public/images/JM image.png",
      "firstName": "Jenny",
      "lastName": "McDermott",
      "email": "Jenny.McDermott@dummyapis.com",
      "contactNumber": "4486799002",
      "age": 34,
      "dob": "08/01/1990",
      "address": "Address8",
      "designation": "Researcher",
      "managerId": 1002
    },
    {
      "id": 1009,
      "imageUrl": "../public/images/PM image.png",
      "firstName": "Phyllis",
      "lastName": "McGlynn",
      "email": "Phyllis.McGlynn@dummyapis.com",
      "contactNumber": "4800894601",
      "age": 84,
      "dob": "25/12/1940",
      "address": "Address9",
      "designation": "Researcher",
      "managerId": 1003
    },
    {
      "id": 1010,
      "imageUrl": "../public/images/GA image.png",
      "firstName": "Gregory",
      "lastName": "Aufderhar",
      "email": "Gregory.Aufderhar@dummyapis.com",
      "contactNumber": "4406990862",
      "age": 24,
      "dob": "02/02/2000",
      "address": "Address10",
      "designation": "Developer",
      "managerId": 1003
    }
  ]